#!/usr/bin/env python3

import sys
import socket

ClientSocket = socket.socket()
host = '192.168.56.9'
port = 8888

print('Waiting for connection')

try:
    ClientSocket.connect((host, port))
except socket.error as e:
    print(str(e))

Response = ClientSocket.recv(1024)
print(Response.decode('utf-8'))
cResponse = 'Client 1 has been connected!'
ClientSocket.send(cResponse.encode('utf-8'))

while True:

    print('\nMathematical Function')
    print('[1] Logarithmic Function (Log)')
    print('[2] Square Root Function (Sqrt)')
    print('[3] Exponential Function (Exp)')
    print('[4] Degree Function (Deg)')
    print('[5] Radian Function (Rad)')
    print('[e] Exit system')
    option = input('ENTER WHICH MATHEMATICAL FUNCTION DO YOU WANT TO USE: ')

    if option == '1' or option == '2' or option == '3' or option == '4' or option == '5':
        value = input('ENTER A VALUE: ')
        option = option + ':' + value
        ClientSocket.send(str.encode(option))

    elif option == 'e':
        print('SYSTEM EXIT')
        ClientSocket.send(str.encode(option))
	sys.exit()

    else:
        print('NOT VALID INPUT!')
        sys.exit()

    Response = ClientSocket.recv(1024)
    print(Response.decode('utf-8'))

ClientSocket.close()
